<?php
$samhost = $sam["host"];
$samport = $sam["port"];
$errno = '';
$errstr = '';
$dedicated = false;

$songid = intval($_GET['songid']);

$host = $_SERVER['REMOTE_ADDR'];

$request = "GET /req/?songID=$songid&host=".urlencode($host)." HTTP\1.0\r\n\r\n";

$xmldata = "";
// @ in front of something means to completely suppress any errors generated by it...
// Make a call to the sam server to request the song to be played
$fd = fsockopen($samhost,$samport, $errno, $errstr, 30);

// handle the response
if(!empty($fd))
{
	fputs ($fd, $request);
	$line="";
	while(!($line=="\r\n"))
		{ $line=fgets($fd,128); }	// strip out the header
	while ($buffer = fgets($fd, 4096))
		{  $xmldata  .= $buffer; }
	fclose($fd);
}
else DoError(803, $samhost, $samport, $errno, $errstr, $logo);

if(empty($xmldata)) DoError(804, $samhost, $samport, $errno, $errstr, $logo);
 
//#######################################
//  Initialize data from XML Response
//#######################################
$responseXML = new SimpleXMLElement($xmldata);
$code = $responseXML->status[0]->code;
$message = $responseXML->status[0]->message;
$requestid = $responseXML->status[0]->requestID;

if(empty($code)) DoError(804, $samhost, $samport, $errno, $errstr, $logo);
 
// If successful, pull the song info and print a success message (along with the dedication form)
if ($code == 200) {
	
	$link = new mysqli($db_host, $db_username, $db_password, $db_dbname, $db_port);
	if ($link->connect_errno) {
		die("Failed to connect to database: (" . $link->connect_errno . ") " . $link->connect_error);
	}

	$sql = "SELECT songlist.*, songlist.ID as songID FROM songlist WHERE songlist.ID = $songid";
	$result = $link->query($sql);
	$song = $result->fetch_assoc();
	$song["requestid"] = $requestid;
	
	require("req/req.success.html");
	
} else {
	require("req/req.failed.html");
}
  
function DoError($code, $samhost, $samport, $errno, $errstr, $logo)  
{
 
 
 switch ($code)
 {
  case 800 : $message = "SAM host must be specified"; break;
  case 801 : $message = "SAM host can not be 127.0.0.1 or localhost"; break;
  case 802 : $message = "Song ID must be valid";  break;
  case 803 : $message = "Unable to connect to $samhost:$samport. Station might be offline.<br>The error returned was $errstr ($errno).";  break;
  case 804 : $message = "Invalid data returned!";  break;
 }
 require("req/req.failed.html"); 
 exit;
}
?>
